#!/bin/sh

# Make rbenv work on weird environments
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null 2>&1; then
    eval "$(rbenv init -)"

    export RBENV_VERSION=`cat .rbenv-version`
    exec_cmd="rbenv exec"
fi
$exec_cmd bundle install --path .bundle
$exec_cmd bundle exec rake spec
